// Builds src/tvclubs.js: every club with a MATCHi TV camera (courts.padelgo.tv/Courts, public), as [clubId, name,
// [courts]]. node tv-clubs.mjs (the list bundled in the worker), or node tv-clubs.mjs --json <file> (the weekly
// GitHub Action: tvclubs.json on the branch "tvdata", which the worker reads once a day).
import { writeFileSync } from "node:fs";
const list = await (await fetch("https://courts.padelgo.tv/Courts")).json();
const by = new Map();
for (const c of list) {
  const m = /^(.*?)\s+(?:på|at)\s+(.+)$/.exec(String(c.description || "").trim());
  if (!m) continue;
  const name = m[2].replace(/\s+EXTERNAL$/i, "").trim(), court = m[1].trim();
  const x = by.get(c.clubId + "|" + name) || [c.clubId, name, []];
  if (!x[2].includes(court)) x[2].push(court);
  by.set(c.clubId + "|" + name, x);
}
const out = [...by.values()].sort((a, b) => a[1].localeCompare(b[1]));
if (out.length < 100) throw new Error("only " + out.length + " clubs: not written");
const j = process.argv.indexOf("--json");
if (j > 0) { writeFileSync(process.argv[j + 1], JSON.stringify(out)); console.log(out.length + " clubs -> " + process.argv[j + 1]); process.exit(0); }
writeFileSync(new URL("./src/tvclubs.js", import.meta.url),
  "// MATCHi TV clubs with cameras: [clubId, name, courts]. Generated by tv-clubs.mjs (" + new Date().toISOString().slice(0, 10) + ").\nexport default " + JSON.stringify(out) + ";\n");
console.log(out.length + " clubs");
